// Shared constants for the survey

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' }
];

export const INDUSTRIES = [
  'AI / Machine Learning',
  'AR / VR / Spatial Computing',
  'Biotech',
  'Climate / Clean Energy',
  'Consumer / D2C',
  'Cybersecurity',
  'E-commerce',
  'Edtech',
  'Fintech',
  'Food & Beverage / Foodtech',
  'Gaming / Entertainment',
  'Hardware / IoT',
  'Healthtech / Medtech',
  'HR / Future of Work',
  'Legaltech / Regtech',
  'Logistics / Supply Chain',
  'Media / Creator Economy',
  'Mobility / Transportation',
  'Proptech / Real Estate',
  'Social Impact / Nonprofit Tech',
  'Software / SaaS',
  'Sustainability / Carbon Tech',
  'Travel / Hospitality',
  'Web3 / Blockchain / Crypto',
  'Other'
];

export const ROLES = [
  'Community / content',
  'Customer success / support',
  'Engineering / development',
  'Finance / operations',
  'Fundraising',
  'Hiring / culture',
  'Legal / compliance',
  'Marketing / growth',
  'Product strategy',
  'Sales / business development',
  'UX / design',
  'Other'
];

export const MAJOR_DECISIONS = [
  'Accepting advisors',
  'Accepting investors',
  'Equity allocations',
  'Hiring key personnel',
  'Major partnerships or contracts',
  'Product pivots',
  'Raising funding',
  'Selling the company or merging',
  'None of the above',
  'Other'
];

export const TERMINATION_CONSEQUENCES = [
  'Formal warning and performance plan',
  'Reduction or dilution of unvested equity',
  'Role reassignment or demotion',
  'Temporary suspension of voting rights'
];

export const SECTIONS = [
  { id: 1, name: 'Formation & Purpose' },
  { id: 2, name: 'Cofounder Info' },
  { id: 3, name: 'Equity Allocation' },
  { id: 4, name: 'Decision-Making' },
  { id: 5, name: 'Equity & Vesting' },
  { id: 6, name: 'IP & Ownership' },
  { id: 7, name: 'Compensation' },
  { id: 8, name: 'Performance' },
  { id: 9, name: 'Non-Competition' },
  { id: 10, name: 'Final Details' }
];
